### ISSUE TITLE
全局过滤

### ISSUE THREAD

**Issue by OnlyMyRailgun** [ditclear/DataBinding-AspectJ#1]
请问如何不用注解，直接进行全局过滤，应该include谁呢？

**Comment by ditclear** [comment]
定义注解只是用来作为一个切面而已，你可以在你自己的Aspcet类里自己去写自己的切面
当前定义的切面是@com.ditclear.app.aop.annotation.SingleClick * *(..)。
如果不自定义注解，pointCut可以写成public void android.view.View.OnClickListener.onClick(..)，以onclick方法为切入面，不过这样估计所以点击事件都会进行防抖处理。
具体AspectJX相关的问题，建议去apectjx问问<https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx>

**Comment by OnlyMyRailgun** [comment]
@ditclear 解决了，多谢！
